### ISSUE TITLE
Exporting hangs forever

### ISSUE THREAD

**Issue by d10i** [endurabyte/FitEdit#12]
# Steps to reproduce
1. Import [15535326668.zip](https://github.com/endurabyte/FitEdit/files/15415979/15535326668.zip) after extracting it. This is a pool swimming session that was exported directly from Garmin Connect
2. Load it (Select it -> Selection -> Load)
3. Export (Select it -> Selection -> Export)

Hangs forever on both Windows and Linux. One CPU core is 100% busy doing something the whole time.

It seems to do something specific to this file. Interestingly, if another file is imported, loaded, exported and unloaded first, then exporting this file using the steps above works fine.

**Comment by nref** [comment]
Thanks for the report. I'll also have a look at this ASAP

**Comment by nref** [comment]
Fixed in 4.7.0. The issue was in the Garmin FIT SDK which FitEdit depends on. The SDK would enter an infinite loop writing certain string fields. 

In particular, the OP's FIT file contained `WorkoutStep` fields which activated this failure mode. AFAIK this is the first time FitEdit had been asked to load `WorkoutStep` fields. They now load as expected.

Good bug!
